=== syngenta-digital/package-python-adapt/pyadapt/schemas/Operation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Operation",
  "type": "object",
  "properties": {
    "aliases": {
      "description": "Array of UniqueId objects that allows multiple identifiers to be attached to this object. In this instance, it would contain the EXTERNAL identifier for the chunk of data this document represents.",
      "type": "array",
      "items": {
        "$ref": "UniqueId.schema.json#"
      }
    },
    "allocation": {
      "$ref": "Allocation.schema.json#"
    },
    "asset_uses": {
      "description": "Array of objects that capture the allocation of asset resources to this field operation.",
      "type": "array",
      "items": {
        "$ref": "AssetUse.schema.json#"
      }
    },
    "assets": {
      "description": "Array of Asset objects that define the identity of the equipment resources used in the field operation.",
      "type": "array",
      "items": {
        "$ref": "Asset.schema.json#"
      }
    },
    "attachments": {
      "description": "Array of objects that provide links to attached files/objects.",
      "type": "array",
      "items": {
        "$ref": "AttachmentLink.schema.json#"
      }
    },
    "boundaries": {
      "description": "Array of FieldBoundary objects that refine spatial context of this document.",
      "type": "array",
      "items": {
        "$ref": "FieldBoundary.schema.json#"
      }
    },
    "bounding_box": {
      "description": "GeoJSON bounding box as defined in rfc7946 section 5.0 (xMin, yMin, xMax, yMax)",
      "type": "array",
      "items": {
        "type": "number",
        "format": "double"
      },
      "maxItems": 4,
      "minItems": 4
    },
    "created": {
      "description": "Created timestamp of this object within the Cropwise system. ISO-8601 UTC expected.",
      "type": "string",
      "format": "date-time"
    },
    "crop": {
      "$ref": "Crop.schema.json#"
    },
    "cropzones": {
      "description": "Array of CropZone objects that give spatial, temporal, and crop context to this document.",
      "type": "array",
      "items": {
        "$ref": "CropZone.schema.json#"
      }
    },
    "description": {
      "description": "Friendly name label meant to help the selection of this particular chunk of data from a list.",
      "type": "string"
    },
    "document_state": {
      "$ref": "common-enums.schema.json#/definitions/DocumentStateEnum"
    },
    "document_type": {
      "$ref": "common-enums.schema.json#/definitions/DocumentTypeEnum"
    },
    "environmental_conditions": {
      "description": "Array of Obs that capture the environmental conditions related to this field operation.",
      "type": "array",
      "items": {
        "$ref": "Obs.schema.json#"
      }
    },
    "farms": {
      "description": "Array of Farm objects that give context to the Field objects included in this document.",
      "type": "array",
      "items": {
        "$ref": "Farm.schema.json#"
      }
    },
    "fields": {
      "description": "Array of Field objects that give spatial context to this document.",
      "type": "array",
      "items": {
        "$ref": "Field.schema.json#"
      },
      "minItems": 1
    },
    "grower": {
      "$ref": "Grower.schema.json#"
    },
    "id": {
      "description": "Globally unique INTERNAL identifier for the chunk of data that this document represents. ",
      "type": "string",
      "format": "uuid"
    },
    "integration_account_ref": {
      "description": "Id of the Cropwise IntegrationAccount that this data originated in.",
      "type": "string",
      "format": "uuid_uuid"
    },
    "land_uses": {
      "description": "Array of objects that capture the allocation of land (Field/CropZone) resources to this field operation.",
      "type": "array",
      "items": {
        "$ref": "LandUse.schema.json#"
      },
      "minItems": 1
    },
    "modified": {
      "description": "Modified timestamp of this object within the Cropwise system. ISO-8601 UTC expected.",
      "type": "string",
      "format": "date-time"
    },
    "notes": {
      "description": "Array of note objects.",
      "type": "array",
      "items": {
        "$ref": "Note.schema.json#"
      }
    },
    "operation_types": {
      "description": "Array of operational classification values that communicate the type(s) of field operation(s) this document describes.",
      "type": "array",
      "items": {
        "$ref": "common-enums.schema.json#/definitions/OperationTypeEnum"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "organization_ref": {
      "description": "Id of the Cropwise Organization that this data is associated with.",
      "type": "string",
      "format": "uuid"
    },
    "parties": {
      "description": "Array of Party objects that define the identity of the person/company resources used in the field operation.",
      "type": "array",
      "items": {
        "$ref": "Party.schema.json#"
      }
    },
    "party_uses": {
      "description": "Array of objects that capture the allocation of party resources to this field operation.",
      "type": "array",
      "items": {
        "$ref": "PartyUse.schema.json#"
      }
    },
    "product_uses": {
      "description": "Array of objects that capture the allocation of product resources to this field operation.",
      "type": "array",
      "items": {
        "$ref": "ProductUse.schema.json#"
      },
      "minItems": 1
    },
    "products": {
      "description": "Array of Product objects that define the identity of the product resources used in the field operation.",
      "type": "array",
      "items": {
        "$ref": "Product.schema.json#"
      }
    },
    "spatial_properties": {
      "description": "Array of objects that describe the meaning of Feature properties in the high-density spatial data.",
      "type": "array",
      "items": {
        "$ref": "SpatialProperty.schema.json#"
      }
    },
    "status": {
      "$ref": "common-enums.schema.json#/definitions/StatusEnum"
    },
    "task_measures": {
      "description": "Array of RepresentationValues that captures whole-task totals like time and area.",
      "type": "array",
      "items": {
        "$ref": "RepresentationValue.schema.json#"
      }
    },
    "time_scopes": {
      "description": "Array of TimeScopes (semantically scoped time objects). This is where crop season, crop year, start time, end time, etc. are encoded.",
      "type": "array",
      "items": {
        "$ref": "TimeScope.schema.json#"
      }
    },
    "version": {
      "description": "Integer representing the version number of this object.",
      "type": "integer"
    }
  },
  "additionalProperties": false,
  "required": [
    "fields",
    "id",
    "land_uses",
    "operation_types",
    "product_uses"
  ]
}

=== syngenta-digital/package-python-adapt/tests/pyadapt/schemas/fd16a7c3-5706-a535-c973-523cf3ae861b-summary.json
{
    "id": "fd16a7c3-5706-a535-c973-523cf3ae861b",
    "aliases": [
        {
            "id": "3c9d1165-70fd-4464-898e-9bb052204397_e6db9249-50d5-492e-87b5-60196f6b0a2a",
            "model_scope": "DOCUMENT",
            "system_type": "LAND_DB",
            "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
        }
    ],
    "version": 0,
    "integration_account_ref": "8cbad13e-e1be-43f3-94b5-c87508729088_7dd77324-0604-4f44-90e5-ee892d9ed930",
    "organization_ref": "7dd77324-0604-4f44-90e5-ee892d9ed930",
    "description": "First Choice Stylet Oil, First Choice Spray Kicker, Quilt",
    "document_type": "WORK_RECORD",
    "document_state": "DONE",
    "operation_types": [
        "APPLICATION"
    ],
    "time_scopes": [
        {
            "description": "2004",
            "date_context": "CROP_YEAR",
            "iso_time": "2004-01-01T00:00:00Z"
        },
        {
            "description": "START",
            "date_context": "ACTUAL_START",
            "iso_time": "2004-05-17T14:00:00Z"
        },
        {
            "description": "END",
            "date_context": "ACTUAL_END",
            "iso_time": "2004-05-18T00:00:00Z"
        }
    ],
    "grower": {
        "id": "1e285193-1b90-f6bb-7795-a99af3dd9de6",
        "aliases": [
            {
                "id": "6c385c28-f42b-4c60-868b-edc0e7acac1c",
                "model_scope": "GROWER",
                "system_type": "LAND_DB",
                "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
            },
            {
                "id": "0012400000fB0bBAAS",
                "model_scope": "GROWER",
                "system_type": "LAND_DB",
                "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
            }
        ],
        "description": "L3 Farms",
        "is_resolved": false
    },
    "farms": [
        {
            "id": "0d66e68a-2880-c157-5d21-f5fe2c85c402",
            "aliases": [
                {
                    "id": "e5dbb876-ce72-4c3e-b067-17c5a6e77be3",
                    "model_scope": "FARM",
                    "system_type": "LAND_DB",
                    "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
                }
            ],
            "description": "Shedd",
            "grower_ref": "1e285193-1b90-f6bb-7795-a99af3dd9de6",
            "is_resolved": false
        }
    ],
    "fields": [
        {
            "id": "401f8408-f9fb-5870-69f9-918ccbd7d711",
            "aliases": [
                {
                    "id": "5d2ee5cb-44e6-4d13-96f7-45c9c88fe692",
                    "model_scope": "FIELD",
                    "system_type": "LAND_DB",
                    "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
                }
            ],
            "description": "Cemetary East",
            "grower_ref": "1e285193-1b90-f6bb-7795-a99af3dd9de6",
            "farm_ref": "0d66e68a-2880-c157-5d21-f5fe2c85c402",
            "active_boundary_ref": "e92ab7e8-893e-8229-6c2b-86ef2975439b",
            "is_resolved": false
        }
    ],
    "cropzones": [
        {
            "id": "378cbcb6-21f5-a0c5-f7ee-39ed40baaa2b",
            "aliases": [
                {
                    "id": "e6db9249-50d5-492e-87b5-60196f6b0a2a",
                    "model_scope": "CROPZONE",
                    "system_type": "LAND_DB",
                    "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
                }
            ],
            "description": "Cemetary East",
            "time_scopes": [
                {
                    "description": "2004",
                    "date_context": "CROP_YEAR",
                    "iso_time": "2004-01-01T00:00:00Z"
                }
            ],
            "field_ref": "401f8408-f9fb-5870-69f9-918ccbd7d711",
            "crop_ref": "3FESC",
            "is_resolved": false
        }
    ],
    "crop": {
        "id": "3FESC",
        "aliases": [
            {
                "id": "e0c2d768-5ad4-4947-a5ef-133b346f6d2e",
                "model_scope": "CROP",
                "system_type": "LAND_DB",
                "instance_system_id": "6c385c28-f42b-4c60-868b-edc0e7acac1c"
            }
        ],
        "description": "Tall Fescue",
        "is_resolved": true
    },
    "products": [
        {
            "id": "48810292-c0b9-47cc-a85b-dd45ce24b5fd",
            "aliases": [
                {
                    "id": "48810292-c0b9-47cc-a85b-dd45ce24b5fd",
                    "model_scope": "PRODUCT",
                    "system_type": "LAND_DB",
                    "instance_system_id": "00000000-0000-0000-0000-000000000000"
                }
            ],
            "description": "First Choice Stylet Oil",
            "product_type": "CROP_PROTECTION",
            "is_resolved": true
        },
        {
            "id": "898aba7c-1feb-4b75-b67e-5a86eeed2896",
            "aliases": [
                {
                    "id": "898aba7c-1feb-4b75-b67e-5a86eeed2896",
                    "model_scope": "PRODUCT",
                    "system_type": "LAND_DB",
                    "instance_system_id": "00000000-0000-0000-0000-000000000000"
                }
            ],
            "description": "First Choice Spray Kicker",
            "product_type": "CROP_NUTRITION",
            "is_resolved": true
        },
        {
            "id": "c899b704-76c5-4e6e-96ec-956900a6cccd",
            "aliases": [
                {
                    "id": "c899b704-76c5-4e6e-96ec-956900a6cccd",
                    "model_scope": "PRODUCT",
                    "system_type": "LAND_DB",
                    "instance_system_id": "00000000-0000-0000-0000-000000000000"
                }
            ],
            "description": "Quilt",
            "product_type": "CROP_PROTECTION",
            "is_resolved": true
        }
    ],
    "parties": [],
    "land_uses": [
        {
            "resource_type": "CROPZONE",
            "resource_ref": "378cbcb6-21f5-a0c5-f7ee-39ed40baaa2b",
            "resource_measures": [
                {
                    "dtr_code": "A_AREA_ALLOCATED",
                    "value": "56170.367776612992285450",
                    "uom": "m2",
                    "user_uom": "ac"
                },
                {
                    "dtr_code": "A_TIME_ALLOCATED",
                    "value": "1795.6660816990870223067990468",
                    "uom": "sec",
                    "user_uom": ""
                }
            ]
        }
    ],
    "party_uses": [],
    "product_uses": [
        {
            "resource_type": "PRODUCT",
            "resource_ref": "48810292-c0b9-47cc-a85b-dd45ce24b5fd",
            "resource_measures": [
                {
                    "dtr_code": "A_AREA_ALLOCATED",
                    "value": "56170.3677766129922854500",
                    "uom": "m2",
                    "user_uom": "ac"
                },
                {
                    "dtr_code": "A_ACT_VOL_PER_AREA",
                    "value": "0.0000730777841631455755971693",
                    "uom": "l1[m2]-1",
                    "user_uom": "floz1ac-1"
                },
                {
                    "dtr_code": "A_ACT_VOL_TOTAL",
                    "value": "4.1048060127438314842499988276",
                    "uom": "l",
                    "user_uom": ""
                }
            ]
        },
        {
            "resource_type": "PRODUCT",
            "resource_ref": "898aba7c-1feb-4b75-b67e-5a86eeed2896",
            "resource_measures": [
                {
                    "dtr_code": "A_AREA_ALLOCATED",
                    "value": "56170.3677766129922854500",
                    "uom": "m2",
                    "user_uom": "ac"
                },
                {
                    "dtr_code": "A_ACT_VOL_PER_AREA",
                    "value": "0.0037415824938014479891036016",
                    "uom": "l1[m2]-1",
                    "user_uom": "gal1ac-1"
                },
                {
                    "dtr_code": "A_ACT_VOL_TOTAL",
                    "value": "210.16606474336413507336000250",
                    "uom": "l",
                    "user_uom": ""
                }
            ]
        },
        {
            "resource_type": "PRODUCT",
            "resource_ref": "c899b704-76c5-4e6e-96ec-956900a6cccd",
            "resource_measures": [
                {
                    "dtr_code": "A_AREA_ALLOCATED",
                    "value": "56170.3677766129922854500",
                    "uom": "m2",
                    "user_uom": "ac"
                },
                {
                    "dtr_code": "A_ACT_VOL_PER_AREA",
                    "value": "0.000102308897828403805836037",
                    "uom": "l1[m2]-1",
                    "user_uom": "floz1ac-1"
                },
                {
                    "dtr_code": "A_ACT_VOL_TOTAL",
                    "value": "5.7467284178413640779499972352",
                    "uom": "l",
                    "user_uom": ""
                }
            ]
        }
    ],
    "task_measures": [
        {
            "dtr_code": "A_AREA_TOTAL",
            "value": "56170.367776612992285450",
            "uom": "m2",
            "user_uom": "ac"
        },
        {
            "dtr_code": "A_TIME_TOTAL",
            "value": "1795.6660816990870223067990468",
            "uom": "sec",
            "user_uom": ""
        }
    ],
    "attachments": [
        {
            "description": "Source",
            "attachment_type": "SOURCE_SUMMARY_DATA",
            "uri": "https://prod-ingestor-data.s3.us-east-2.amazonaws.com/raw/land_db/8cbad13e-e1be-43f3-94b5-c87508729088_7dd77324-0604-4f44-90e5-ee892d9ed930/operation/6c385c28-f42b-4c60-868b-edc0e7acac1c.zip"
        },
        {
            "description": "Canonical Summary Data",
            "attachment_type": "NORMALIZED_SUMMARY_DATA",
